build.gradle.kts, gradle.properties, settings.gradle.kts, src/main/kotlin/kr/wooco/woocobe/common/config/IdGeneratorConfig.kt, src/main/kotlin/kr/wooco/woocobe/common/domain/IdGenerator.kt, src/main/kotlin/kr/wooco/woocobe/common/domain/UseCase.kt, src/main/kotlin/kr/wooco/woocobe/common/storage/BaseTimeEntity.kt, src/main/resources/application-local.yml
프로젝트 초기 개발을 위해 레이어간의 컨벤션 및 공용 로직 추가
- ✨ `UseCase` SAM 인터페이스 추가
- ✨ JPA 설정 및 기본 엔티티 클래스 추가
- ✨ ID 생성 로직 추가
- closed #3 
-
=> feat: 레이어 컨벤션 설정 및 공용 로직 추가

docker/docker-compose.yml, docker/init.sql, src/test/kotlin/kr/wooco/woocobe/support/KotestConfig.kt, src/test/kotlin/kr/wooco/woocobe/support/MysqlCleaner.kt, src/test/kotlin/kr/wooco/woocobe/support/RedisCleaner.kt, src/test/kotlin/kr/wooco/woocobe/support/TestAnnotation.kt, src/test/resources/application-test.yml, src/test/resources/kotest.properties
테스트 코드를 작성할 수 있는 기초 테스트 코드 설정 추가
- ✨ Kotest 실행 환경 설정 추가
- ✨ 테스트 프로필에 대한 프로퍼티 설정 추가
- closed #9 
-
=> test: 테스트 코드 초기 구성 추가

src/main/kotlin/kr/wooco/woocobe/common/config/LoggingConfig.kt, src/main/kotlin/kr/wooco/woocobe/common/exception/BaseErrorCode.kt, src/main/kotlin/kr/wooco/woocobe/common/exception/CustomException.kt, src/main/kotlin/kr/wooco/woocobe/common/exception/GlobalExceptionHandler.kt, src/main/kotlin/kr/wooco/woocobe/common/logging/MdcLoggingFilter.kt, src/main/kotlin/kr/wooco/woocobe/common/logging/ReqResLoggingFilter.kt
기본적으로 사용될 예외 클래스와 로깅 필터를 추가합니다.
- ✨ 로깅 필터 추가
- ✨ 전역 예외 클래스 추가
- closed #14 
-
=> feat: 로깅 필터 및 예외 클래스 추가

src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/CourseCommentStorageGateway.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/InterestCourseStorageGateway.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseComment.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/model/InterestCourse.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseCommentUseCase.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddInterestCourseUseCase.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteCourseCommentUseCase.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteInterestCourseUseCase.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseCommentUseCase.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllMyInterestCourseUseCase.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetCourseUseCase.kt, src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseCommentUseCase.kt, src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/JpaCourseCommentStorageGateway.kt, src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/JpaInterestCourseStorageGateway.kt, src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCommentEntity.kt, src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCommentJpaRepository.kt, src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/InterestCourseEntity.kt, src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/InterestCourseJpaRepository.kt
관심 코스 및 코스 댓글을 위한 도메인 기능과 인프라 구현체를 추가합니다
- ✨ 관심 코스 도메인 기능 추가
- ✨ 코스 댓글 도메인 기능 추가
- closed #28 
-
=> feat: 관심 코스 및 코스 댓글 도메인 기능 추가

src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/AuthTokenStorageGateway.kt, src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/AuthUserStorageGateway.kt, src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/TokenProviderGateway.kt, src/main/kotlin/kr/wooco/woocobe/auth/domain/model/AuthToken.kt, src/main/kotlin/kr/wooco/woocobe/auth/domain/model/AuthUser.kt, src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/LogoutUseCase.kt, src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/ReissueTokenUseCase.kt, src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCase.kt, src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/WithdrawUseCase.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/KakaoOAuthRestClient.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/JpaAuthUserStorageGateway.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/JwtTokenProviderGateway.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/RedisAuthTokenStorageGateway.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/RestSocialAuthClientGateway.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthTokenEntity.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthTokenRedisRepository.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserEntity.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserJpaRepository.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/token/JWTProvider.kt, src/main/kotlin/kr/wooco/woocobe/auth/ui/web/AuthController.kt, src/main/kotlin/kr/wooco/woocobe/common/security/JwtAuthenticationFilter.kt, src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/LogoutUseCaseTest.kt, src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/ReissueTokenUseCaseTest.kt, src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCaseTest.kt, src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/WithdrawUseCaseTest.kt
기존에 구현한 인증 및 인가 로직 리팩토링 작업과 함께 회원탈퇴 기능을 추가합니다
- ✨ 인증 인가 로직 수정
- ✨ 회원탈퇴 기능 추가
- closed #34 
-
=> refactor: 인증 및 인가 로직 수정 및 회원탈퇴 추가

src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceReviewStorageGateway.kt
플레이스 도메인에서 발생한 컴파일 오류를 해결합니다.
- ✨ 매퍼 로직에서 회원 도메인에 대한 의존성이 삭제되지 않은 부분 삭제
- closed #43 
- PR 올리기전에 로컬 환경에서 테스트 한번 돌리고 올려주시면 감사합니다..
=> fix: 플레이스 컴파일 오류 해결

.github/workflows/pull-request-ci.yml
CI 테스트시 gradle 캐싱이 제대로 동작하지 않고 있는 오류를 수정합니다.
- ✨ Github Actions CI 스크립트 수정
- closed #56 
-
=> fix: Github Actions CI 스크립트 캐싱 오류 수정

build.gradle.kts, gradle.properties, src/main/kotlin/kr/wooco/woocobe/auth/ui/config/AuthIgnorePaths.kt, src/main/kotlin/kr/wooco/woocobe/common/domain/exception/BaseErrorCode.kt, src/main/kotlin/kr/wooco/woocobe/common/ui/config/JacksonConfig.kt, src/main/kotlin/kr/wooco/woocobe/common/ui/config/SwaggerConfig.kt, src/main/kotlin/kr/wooco/woocobe/common/ui/web/GlobalApiResponseAdvice.kt, src/main/kotlin/kr/wooco/woocobe/common/ui/web/GlobalExceptionAdvice.kt, src/main/resources/application-local.yml
전역 API 응답 설정과 API 문서화를 위해 스웨거 설정을 추가합니다
- ✨ 공통 API 응답 설정 추가
- ✨ 스웨거 설정 추가
- closed #38 
-
=> feat: 전역 API 응답 설정 및 스웨거 추가

src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CoursePlaceJpaEntity.kt
코스 장소 테이블에서 장소 순서에 대한 컬럼명을 수정합니다
- ✨ 장소 순서에 대한 컬럼명 수정
- closed #65 
MySQL 예약어와 충돌 이슈 해결
=> fix: 코스 장소 순서 컬럼명 수정

.github/workflows/deploy-dev.yml, .github/workflows/pr-ci-test.yml, .github/workflows/pull-request-ci.yml, Dockerfile, build.gradle.kts
개발 서버 배포 스크립트와 헬스 체크를 위한 엑츄에이터 의존성을 추가합니다.
- ✨ 엑츄에이터 의존성 추가
- ✨ 개발 서버 배포 스크립트 추가
- ✨ PR CI 스크립트 로직 수정
- closed #84 
-
=> build: 개발 서버 배포 스크립트 및 엑츄에이터 의존성 추가

.github/workflows/deploy-dev.yml, Dockerfile-dev
개발 환경 배포 스크립트를 수정합니다.
- ✨ 개발 환경 `github actions` 스크립트 수정
- ✨ `Dockerfile` 분리
- closed #86 
-
=> fix: 개발 환경 배포 스크립트 수정

src/main/kotlin/kr/wooco/woocobe/auth/ui/web/config/CorsProperties.kt, src/main/kotlin/kr/wooco/woocobe/auth/ui/web/config/WebSecurityConfig.kt, src/main/kotlin/kr/wooco/woocobe/common/ui/config/SwaggerConfig.kt, src/main/kotlin/kr/wooco/woocobe/common/ui/config/WebFilterConfig.kt, src/main/resources/application-local.yml, src/test/resources/application-test.yml
CORS 설정 수정 및 전역 필터가 적용되는 순서를 수정합니다.
- ✨ 스웨거에서 발생한 CORS 오류 수정
- ✨ 전역 예외 핸들러 필터 순서 조정
- ✨ CORS 설정 추가
- closed #91 
-
=> refactor: CORS 설정 및 전역 필터 순서 변경

src/main/kotlin/kr/wooco/woocobe/auth/ui/web/config/AuthIgnorePaths.kt, src/main/kotlin/kr/wooco/woocobe/auth/ui/web/config/WebSecurityConfig.kt, src/main/kotlin/kr/wooco/woocobe/auth/ui/web/filter/JwtAuthenticationFilter.kt
시큐리티 CORS 설정 수정과 JWT 필터에서 예외를 던지지 않도록 수정합니다
- ✨ 스프링 시큐리티 CORS 설정 수정
- ✨ JWT 필터 예외를 던지지 않도록 수정
- closed #96 
-
=> refactor: CORS 설정 및 시큐리티 필터 수정

src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt, src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
- 리뷰 이미지 처리 로직을 개선
1. **리뷰 이미지 처리 로직 개선**
- 리뷰 작성 시 첫 번째 이미지 URL을 사용해 장소의 썸네일 이미지를 업데이트하도록 로직 수정.
- `imageUrls.firstOrNull()`을 활용하여 이미지가 없을 경우 안전하게 처리.
2. **메서드명 수정**
- `updateMainImageUrl` → `updateThumbnailUrl`로 변경.
- closed #107
=> refactor: 리뷰 이미지 처리 로직 개선 및 함수명 수정

src/main/kotlin/kr/wooco/woocobe/image/domain/gateway/ImageClientGateway.kt, src/main/kotlin/kr/wooco/woocobe/image/domain/model/Image.kt, src/main/kotlin/kr/wooco/woocobe/image/domain/usecase/GetImageUploadUrlUseCase.kt, src/main/kotlin/kr/wooco/woocobe/image/infrastructure/client/S3ClientHandler.kt, src/main/kotlin/kr/wooco/woocobe/image/infrastructure/client/S3ClientProperties.kt, src/main/kotlin/kr/wooco/woocobe/image/infrastructure/gateway/ImageClientGatewayImpl.kt, src/main/kotlin/kr/wooco/woocobe/image/ui/web/controller/ImageApi.kt, src/main/kotlin/kr/wooco/woocobe/image/ui/web/controller/response/ImageUploadUrlResponse.kt, src/main/kotlin/kr/wooco/woocobe/image/ui/web/facade/ImageFacadeService.kt, src/main/resources/application-local.yml, src/test/resources/application-test.yml
이미지 업로드시 업로드된 이미지 주소를 반환하도록 수정하고, 이미지 API 스웨거를 수정합니다.
- ✨ 이미지 주소 반환 로직 추가
- ✨ 이미지 API 스웨거 수정
- closed #109 
-
=> refactor: 업로드된 이미지 주소 반환 로직 및 이미지 API 스웨거 수정

src/main/kotlin/kr/wooco/woocobe/auth/domain/exception/AuthExceptions.kt, src/main/kotlin/kr/wooco/woocobe/auth/domain/model/SocialType.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/cache/repository/PkceRedisRepository.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/SocialAuthClientConfig.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/AuthTokenStorageGatewayImpl.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/PkceStorageGatewayImpl.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/SocialAuthClientGatewayImpl.kt, src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/token/JWTProvider.kt, src/main/kotlin/kr/wooco/woocobe/auth/ui/web/config/AuthIgnorePaths.kt, src/main/kotlin/kr/wooco/woocobe/auth/ui/web/controller/AuthApi.kt
인증 예외 처리 클래스와 인증이 필요 없는 경로를 추가합니다.
- ✨ 인증 예외 처리 추가
- ✨ 미인증 경로 추가
- ✨ 스웨거에서 필요하지 않는 어노테이션 추가
- closed #100 
-
=> refactor: 인증 예외 처리 추가 및 미인증 경로 추가

src/main/kotlin/kr/wooco/woocobe/course/domain/exception/CourseExceptions.kt, src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/InterestCourseStorageGatewayImpl.kt, src/main/kotlin/kr/wooco/woocobe/user/domain/exception/UserExceptions.kt, src/main/kotlin/kr/wooco/woocobe/user/infrastructure/gateway/UserStorageGatewayImpl.kt
회원 예외 처리 로직을 추가합니다.
- ✨ 예외 처리 로직 추가
- closed #99 
-
=> refactor: 회원 예외 처리 추가

src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/RegionApi.kt, src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/RegionController.kt, src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/request/CreatePreferenceRegionRequest.kt, src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/response/CreatePreferenceRegionResponse.kt, src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/response/PreferenceDetailResponse.kt, src/main/kotlin/kr/wooco/woocobe/region/adapter/out/presistence/PreferenceRegionMapper.kt, src/main/kotlin/kr/wooco/woocobe/region/adapter/out/presistence/PreferenceRegionPersistenceAdapter.kt, src/main/kotlin/kr/wooco/woocobe/region/adapter/out/presistence/entity/PreferenceRegionJpaEntity.kt, src/main/kotlin/kr/wooco/woocobe/region/adapter/out/presistence/repository/PreferenceRegionJpaRepository.kt, src/main/kotlin/kr/wooco/woocobe/region/application/command/port/in/AddPreferenceRegionUseCase.kt, src/main/kotlin/kr/wooco/woocobe/region/application/command/port/in/DeletePreferenceRegionUseCase.kt, src/main/kotlin/kr/wooco/woocobe/region/application/command/port/out/DeletePreferenceRegionPort.kt, src/main/kotlin/kr/wooco/woocobe/region/application/command/port/out/LoadPreferenceRegionPort.kt, src/main/kotlin/kr/wooco/woocobe/region/application/command/port/out/SavePreferenceRegionPort.kt, src/main/kotlin/kr/wooco/woocobe/region/application/command/service/RegionCommandService.kt, src/main/kotlin/kr/wooco/woocobe/region/application/query/port/in/GetAllPreferenceRegionUseCase.kt, src/main/kotlin/kr/wooco/woocobe/region/application/query/port/in/GetPreferenceRegionUseCase.kt, src/main/kotlin/kr/wooco/woocobe/region/application/query/port/out/LoadPreferenceRegionDataPort.kt, src/main/kotlin/kr/wooco/woocobe/region/application/query/service/RegionQueryService.kt, src/main/kotlin/kr/wooco/woocobe/region/application/query/service/dto/PreferenceRegionData.kt, src/main/kotlin/kr/wooco/woocobe/region/domain/entity/PreferenceRegion.kt, src/main/kotlin/kr/wooco/woocobe/region/domain/exception/RegionExceptions.kt
회원 선호 지역 기능을 추가합니다.
- ✨ 선호 지역 기능 추가
- closed #123 
인터페이스의 구현체(DI)는 `internal` 키워드로 가시성 제한 했습니다.
=> feat: 회원 선호 지역 기능 추가

src/main/kotlin/kr/wooco/woocobe/common/ui/web/GlobalExceptionAdvice.kt
누락된 쿠키 예외처리 추가 및 개발 환경 프로퍼티 설정을 수정합니다.
- ✨ 누락된 `MissingRequestCookieException` 예외처리 추가
- ✨ 개발 환경 프로퍼티 설정 수정
- closed #131 
-
=> fix: 쿠키 예외처리 추가 및 개발 프로퍼티 설정 수정

src/main/kotlin/kr/wooco/woocobe/user/adapter/in/web/response/UserDetailResponse.kt, src/main/kotlin/kr/wooco/woocobe/user/adapter/out/persistence/UserPersistenceMapper.kt, src/main/kotlin/kr/wooco/woocobe/user/adapter/out/persistence/entity/UserJpaEntity.kt, src/main/kotlin/kr/wooco/woocobe/user/application/port/in/results/UserResult.kt, src/main/kotlin/kr/wooco/woocobe/user/application/service/UserCommandService.kt, src/main/kotlin/kr/wooco/woocobe/user/domain/entity/User.kt, src/main/kotlin/kr/wooco/woocobe/user/domain/vo/UserProfile.kt, src/main/kotlin/kr/wooco/woocobe/user/domain/vo/UserStatus.kt
최초 회원가입시 기본 프로필 정보를 등록할 수 있도록 수정 및 사용자 계정 상태 필드 추가
- ✨ 기본 프로필 정보 추가
- ✨ 회원 계정 상태 필드 추가
- closed #136 
-
=> refactor: 회원 프로필 검증 로직 수정 및 상태 추가

src/main/kotlin/kr/wooco/woocobe/place/application/port/in/result/PlaceResult.kt
- PlaceResult contents 매핑 오류 수정 
- ✨PlaceResult contents 매핑을 value 값으로 수정했습니다.
- closed #149 
-
=> fix: PlaceResult contents 매핑 오류 수정 

bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/common/config/AsyncConfig.kt, bootstrap/api/src/main/resources/application.yml
비동기 쓰레드 설정을 추가합니다
- ✨ 비동기 쓰레드 설정을 추가합니다
- closed #165 
-
=> feat: 스프링 비동기 쓰레드 설정 추가

core/src/main/kotlin/kr/wooco/woocobe/core/coursecomment/domain/event/CourseCommentCreateEvent.kt
댓글 생성 이벤트의 필드를 수정합니다.
- ✨ 댓글 생성 이벤트 필드 수정
- closed #159 
-
=> refactor: 댓글 생성 이벤트 필드 수정

.github/workflows/deploy-dev.yml, .github/workflows/pr-ci-test.yml, bootstrap/api/build.gradle.kts
배포 및 테스트 스크립트에서 환경변수 정의 방법을 수정합니다
- ✨ api 모듈에서 누락된 metric 모듈 추가
- ✨ 스크립트마다 필요한 환경변수를 따로 관리하도록 수정
- 공용으로 사용되는 환경변수는 Repository 레벨내 정의
- 배포 프로필마다 다르게 사용되는 환경변수는 Environment 레벨내 정의
- closed #177 
-
=> build: 스크립트내 환경변수 관리 로직 수정 및 메트릭 모듈 추가

infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceReviewPersistenceAdapter.kt
- 장소 리뷰 저장 로직 개선을 통한 이미지 저장 문제 수정
- ✨`PlaceReviewPersistenceAdapter`의 리뷰 저장 로직 수정
- closed #222
=> fix: 장소 리뷰 저장 시 이미지 데이터 누락 문제 수정

gradle.properties, infrastructure/mysql/src/main/resources/application-mysql.yml
dependabot 취약점 경고 사항 업데이트와 MySQL 벌크 설정을 추가했습니다.
- ✨ 스프링 부트 버전업 (3.3.6 -> 3.3.11)
- ✨ MySQL bulk 작업을 위해 하이버네이트 설정을 추가했습니다.
- closed #228 
- 스프링 부트 버전 3.4.x 로 올려서 얻는 메리트가 거의 없다고 판단하여 3.4.x 버전으로 올리지 않았슴다.
=> build: 스프링 보안 업데이트 적용 및 MySQL 벌크 설정 추가

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/course/repository/CourseLikeJpaRepository.kt
v1.0.0 버전 핫픽스
- ✨ 회원 페이지에서 좋아요 수 카운트 쿼리에서 누락된 where 문 추가
- ✨ 배포 스크립트에서 환경변수가 적용되지 않는 문제 수정
- 
-
=> hotfix: 좋아요 수 카운트 쿼리 및 배포 스크립트 수정
