team-joytas/wooco-be

src/main/kotlin/kr/wooco/woocobe/user/domain/gateway/UserStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/user/domain/model/User.kt
src/main/kotlin/kr/wooco/woocobe/user/infrastructure/gateway/JpaUserStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserEntity.kt
src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserJpaRepository.kt

인증 및 인가를 구현하기 전 기본적으로 필요한 사용자 생성 로직 추가
- ✨ 기본적인 사용자 도메인 로직 추가
- ✨ 사용자 JPA 엔티티 및 JPA 리포지토리 추가
- closed #5 
-

feat: 사용자 생성 기능 추가

---

src/main/kotlin/kr/wooco/woocobe/plan/domain/gateway/PlanStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/plan/domain/model/Plan.kt
src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanRegionInfo.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/JpaPlanStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanEntity.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanJpaRepository.kt

플랜 도메인에서 기본적으로 필요한 플랜 생성 로직 추가
✨ 기본적인 플랜 도메인 로직 추가
✨ 플랜 JPA 엔티티 및 JPA 리포지토리 추가
- closed #15 
- 유저(User) 도메인 코드와 최대한 컨벤션을 맞추고자 했습니다.
- 추후 장소(Place) 도메인이 추가시 플랜(Plan)에도 장소 정보를 추가해야합니다.
- 장소 저장 로직이 필요합니다.
- 장소 조회 로직이 필요합니다.
- `PlanRegionInfo` 의 경우 지역 정보를 추후 전역으로 관리한다면 변경될 수 있습니다.

feat: 플랜 생성 기능 추가

---

src/main/kotlin/kr/wooco/woocobe/WoocoBeApplication.kt
src/main/kotlin/kr/wooco/woocobe/auth/ui/web/AuthController.kt
src/main/kotlin/kr/wooco/woocobe/common/utils/CookieExtensions.kt
src/main/kotlin/kr/wooco/woocobe/common/utils/SpringContextLoader.kt
src/main/resources/application-local.yml

응답시 쿠키에 새로운 데이터를 추가하거나 삭제할 수 있는 확장 함수 추가
- ✨ 쿠키 프로퍼티 설정 추가
- ✨ 쿠키 핸들링을 위한 확장 함수 추가
- ✨ `refresh_token` 발급시 쿠키에 저장되도록 수정
- closed #20 
-

feat: 쿠키 핸들링 확장 함수 추가 및 적용

---

src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/CourseStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/model/Course.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseCategory.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseRegion.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseSortCondition.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseUseCase.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteCourseUseCase.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseUseCase.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetCourseUseCase.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetUserAllCourseUseCase.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseUseCase.kt
src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/JpaCourseStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCategoryEntity.kt
src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCategoryJpaRepository.kt
src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCustomRepository.kt
src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCustomRepositoryImpl.kt
src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseEntity.kt
src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseJpaRepository.kt

코스 기본 도메인 기능 추가
- ✨ 코스 기본 도메인 로직 추가
- ✨ 코스 엔티티 및 리포지토리 추가
- closed #22 
코스 게이트웨이 구현체 부분의 `save()` 메서드에서 update와 save를 나누지 않아, 임시로 도메인 모델의 `id`값이 0인지 확인하는 분기처리 넣어놨습니다. 이 부분은 추후 리팩토링을 통해서 분리할 예정입니다!
관심 코스 및 코스 댓글 기능 추가 예정입니다!

feat: 코스 도메인 기능 추가

---

src/main/kotlin/kr/wooco/woocobe/user/domain/gateway/UserStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/user/domain/model/User.kt
src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCase.kt
src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCase.kt
src/main/kotlin/kr/wooco/woocobe/user/infrastructure/gateway/JpaUserStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserEntity.kt
src/main/kotlin/kr/wooco/woocobe/user/ui/web/UserController.kt
src/main/kotlin/kr/wooco/woocobe/user/ui/web/dto/request/UpdateUserProfileRequest.kt
src/main/kotlin/kr/wooco/woocobe/user/ui/web/dto/response/GetCurrentUserResponse.kt
src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCaseTest.kt
src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCaseTest.kt

회원 도메인에서 필요한 기능을 추가합니다.
- ✨ 회원 도메인 로직 추가
- ✨ 회원 API 컨트롤러 추가
- ✨ 회원 도메인 유즈 케이스 테스트 코드 추가
- closed #31 
`save()`와 `update()` 메서드를 분리해놨는데 분리한 것이 뭔가 더 명확하게 보여주는 것 같아서 좋지만 뭔가 부족한(?) 애매한(?) 느낌이 듭니다..
infrastructure의 gateway 구현체는 DI로만 사용하기 때문에, 앞으로 개발시 `internal` 키워드를 달아주시는게 좋을 것 같습니다~

feat: 회원 기능 추가

---

.github/workflows/pull-request-ci.yml
src/test/kotlin/kr/wooco/woocobe/support/MysqlCleaner.kt
src/test/resources/application-test.yml

PULL REQUEST 발행시 CI 테스트 및 디스코드 웹훅을 보내도록 Github Actions 스크립트 작성
- ✨ CI 테스트 스크립트 추가
- ✨ 테스트 프로퍼티 설정 변경
- ✨ 데이터베이스 초기화시 연관관계 제거 하도록 변경
- closed #35 
-

feat: CI 테스트 환경 구성 추가

---

src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceReviewStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceOneLineReview.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceReview.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/DeletePlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetAllPlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetPlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetPlaceUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetUserAllPlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/UpdatePlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/ValidateReviewWriterUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceReviewStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceJpaRepository.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewJpaRepository.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewImageEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewJpaRepository.kt

- 장소와 장소 리뷰를 관리하는 도메인 모델 및 관련 UseCase, StorageGateway를 구현했습니다. 
- **도메인 모델 추가**
- `Place`, `PlaceReview`, `PlaceOneLineReview` 도메인 클래스 생성
- 평균 평점, 리뷰 수 업데이트 로직 포함
- **StorageGateway 인터페이스 및 JPA 구현**
- `PlaceStorageGateway`와 `PlaceReviewStorageGateway` 생성
- 관련 JPA 구현 (`JpaPlaceStorageGateway`, `JpaPlaceReviewStorageGateway`)
- **UseCase 구현**
- 장소 추가: `AddPlaceUseCase`
- 장소 조회: `GetPlaceUseCase`
- 리뷰 추가: `AddPlaceReviewUseCase`
- 리뷰 조회: `GetPlaceReviewUseCase`, `GetAllPlaceReviewUseCase`, `GetUserAllPlaceReviewUseCase`
- 리뷰 수정: `UpdatePlaceReviewUseCase`
- 리뷰 삭제: `DeletePlaceReviewUseCase`
- **데이터 저장소 구현**
- JPA 엔티티 및 레포지토리 추가 (`PlaceEntity`, `PlaceReviewEntity`, `PlaceOneLineReviewEntity`)
- closed #23
- 해당 장소에 대한 평균 평점 로직과 한줄평 통계 로직은 아직 고려하고 있습니다. |
- 많이 미숙합니다. 혹독한 피드백 부탁드립니다.

feat: 장소 및 장소 리뷰 관련 기능 추가

---

src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceJpaRepository.kt

- 카카오맵 ID 를 활용해서 장소 정보를 조회할 수 있는 기능 추가
- **`PlaceStorageGateway` 인터페이스 업데이트**
- `getByKakaoMapPlaceId(kakaoMapPlaceId: String): Place` 메서드 추가.
- **`JpaPlaceStorageGateway` 구현**
- `getByKakaoMapPlaceId` 메서드 구현
- **`PlaceJpaRepository` 업데이트**
- `findByKakaoMapPlaceId(kakaoMapPlaceId: String): PlaceEntity` 메서드 추가.
- closed #47

feat: 카카오맵 장소 ID로 장소 조회 기능 추가

---

src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceOneLineReviewStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceOneLineReviewStat.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/DeletePlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetOneLineReviewStatsUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/UpdatePlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceOneLineReviewStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceReviewStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewJpaRepository.kt

- 리뷰 로직에 **평점 계산 및 평균 평점 갱신 기능**을 추가
- 특정 장소에 대한 **한줄평 통계 조회 기능**을 구현
- **평점 계산 로직 업데이트**
- `Place` 모델의 `addReview`, `updateReview`, `deleteReview` 메서드 추가:
- 리뷰 추가/수정/삭제 시 평균 평점과 리뷰 수를 자동으로 갱신하도록 구현.
- **한줄평 통계 조회 기능**
- **도메인**
- `PlaceOneLineReviewStat` 모델 추가: 한줄평 내용과 해당 리뷰 수를 나타내는 데이터 구조.
- `PlaceOneLineReviewStorageGateway` 인터페이스 및 `JpaPlaceOneLineReviewStorageGateway` 구현.
- **UseCase**
- `GetOneLineReviewStatsUseCase` 추가:
- 한줄평 통계를 조회하고 반환.
- **쿼리**
- `PlaceOneLineReviewJpaRepository`에 JPQL 쿼리 추가:
- 한줄평 내용과 빈도를 그룹화하여 통계 데이터를 제공.
- **UseCase 수정**
- `AddPlaceReviewUseCase`: 리뷰 추가 시 평점 계산 로직 반영.
- `UpdatePlaceReviewUseCase`: 리뷰 수정 시 평점 업데이트 로직 추가.
- `DeletePlaceReviewUseCase`: 리뷰 삭제 시 평점과 리뷰 수 감소 로직 추가.
- **잘못된 컬럼명 수정**
- `PlaceOneLineReviewEntity`에서 컬럼명을 `placeId`로 변경하고 관련 로직 업데이트.
- …

feat: 장소 리뷰 도메인 평점 계산 및 한줄평 통계 조회 기능 추가

---

src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceJpaRepository.kt

- Place ID 목록을 이용하여 여러 장소 정보를 한 번에 조회할 수 있는 기능을 추가.
- **`PlaceStorageGateway` 업데이트**
- `getAllByPlaceIds(placeIds: List<Long>): List<Place>` 메서드 추가.
- **`JpaPlaceStorageGateway` 업데이트**
- `getAllByPlaceIds` 메서드 구현:
- `PlaceJpaRepository`의 `findAllByIdIn` 메서드를 호출하여 결과를 도메인 객체로 변환.
- **`PlaceJpaRepository` 업데이트**
- `findAllByIdIn(placeIds: List<Long>): List<PlaceEntity>` 메서드 추가:
- Place ID 목록으로 데이터를 조회하는 JPA 메서드 추가.
- closed #61

feat: Place ID 목록으로 Place 조회 기능 추가

---

build.gradle.kts
gradle.properties
src/main/kotlin/kr/wooco/woocobe/image/domain/gateway/ImageClientGateway.kt
src/main/kotlin/kr/wooco/woocobe/image/domain/model/Image.kt
src/main/kotlin/kr/wooco/woocobe/image/domain/model/ImageKey.kt
src/main/kotlin/kr/wooco/woocobe/image/domain/usecase/GetImageUploadUrlUseCase.kt
src/main/kotlin/kr/wooco/woocobe/image/infrastructure/client/S3ClientHandler.kt
src/main/kotlin/kr/wooco/woocobe/image/infrastructure/client/S3ClientProperties.kt
src/main/kotlin/kr/wooco/woocobe/image/infrastructure/gateway/ImageClientGatewayImpl.kt
src/main/kotlin/kr/wooco/woocobe/image/ui/web/controller/ImageApi.kt
src/main/kotlin/kr/wooco/woocobe/image/ui/web/controller/ImageController.kt
src/main/kotlin/kr/wooco/woocobe/image/ui/web/controller/response/ImageUploadUrlResponse.kt
src/main/kotlin/kr/wooco/woocobe/image/ui/web/facade/ImageFacadeService.kt
src/main/resources/application-local.yml
src/test/resources/application-test.yml

이미지 업로드 기능을 추가합니다.
- ✨ AWS S3 의존성 추가
- ✨ Presinged URL 발급 로직 추가
- closed #67 
`ui/web/controller` 패키지안에 `request` 및 `response` 패키지를 두려고 했는데, facade에서 실제 response 객체를 만들어 반환해서 `ui/web` 경로에 `request` 및 `response` 를 두는 방향으로 가야할 것 같습니다.
일단 초기 컨벤션과 일치하기 위해서 `ui/web/controller` 패키지 안에 정의해두고 facade 에서 `ui/web/controller/response`를 참조하도록 구현해놨습니다.

feat: 이미지 업로드 기능 추가

---

src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/BaseTimeEntity.kt
src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/IdGenerator.kt
src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/IdGeneratorConfig.kt
src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/TsidConfig.kt
src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/entity/BaseEntity.kt
src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/entity/BaseTimeEntity.kt

TSID 채번 어노테이션 클래스 추가와 기본 엔티티 클래스를 추가합니다.
기존에 사용하고 있는 기본 엔티티 클래스는 `@Deprecated` 어노테이션 추가했습니다.
- ✨ 커스텀 `TSID` 채번 어노테이션 추가
- ✨ 기본 엔티티 클래스 추가
- ✨ 기존에 사용하던 기본 엔티티 클래스 `@Deprecated` 추가
- closed #72 
-

refactor: 엔티티 식별자 채번 전략 및 기본 엔티티 클래스 수정

---

src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/PlanStorageGatewayImpl.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanCategoryStorageMapper.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanPlaceStorageMapper.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanStorageMapper.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanCategoryJpaEntity.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanJpaEntity.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanPlaceJpaEntity.kt

식별자 생성 전략이 변경됨에 따라 플랜 도메인의 엔티티 클래스 또한 변경하였습니다.
- ✨ 플랜 도메인 내 엔티티 클래스 BaseTimeEntity 변경
- ✨ 플랜 도메인 내 엔티티 클래스 @Tsid 변경
- ✨ 엔티티 클래스 변경에 따른 불필요한 연산자 (!!) 제거
- ✨ 플랜 조회시 잘못된 장소 아이디 값이 반환되던 오류 해결
- closed #77

refactor: 플랜 식별자 생성 전략 수정

---

src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetAllPlaceUseCase.kt

- 다수의 `Place`를 조회할 수 있는 `GetAllPlaceUseCase`를 추가
- 주어진 `placeIds`를 기반으로 장소 목록을 반환하는 기능을 구현
- **`GetAllPlaceUseCase` 추가**
- placeIds에 해당하는 장소 목록을 조회.
- closed #82

feat: GetAllPlaceUseCase 추가

---

src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/DeletePlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/UpdatePlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/PlaceReviewStorageGatewayImpl.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/PlaceStorageGatewayImpl.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewStorageMapper.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceStorageMapper.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceJpaEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceOneLineReviewJpaEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceReviewImageJpaEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceReviewJpaEntity.kt

- 장소와 관련된 주요 메서드들의 네이밍을 개선하고, 코드 스타일을 정리
1. **Place 관련 메서드 네이밍 변경**  
- `addReview` → `increasePlaceStats`
- `updateReview` → `processPlaceStats`
- `deleteReview` → `decreasePlaceStats`
- `getByKakaoMapPlaceId` → `getByKakaoMapPlaceIdOrNull`
2. **로직 리팩토링**  
- Place 관련 로직에서 변수 선언 및 저장 로직 분리.
3. **불필요한 공백 및 스타일 정리**  
- 코드 포맷을 통일하고 불필요한 공백 제거.
- closed #79
1. **`increasePlaceStats`, `processPlaceStats`, `decreasePlaceStats` 네이밍의 이유**  
- **장소(Place)의 상태 변경을 강조:**  
- 리뷰 작업은 장소와 연관되어 있으나, 장소 자체의 상태(averageRating, reviewCount)를 변경하는 것이 로직의 핵심입니다.  
- `Place`를 네이밍에 포함하여 메서드가 "장소"와 관련된 상태 변경임을 직관적으로 이해할 수 있도록 했습니다.  
- 다른 의견 있으면 피드백 부탁 드립니다. 감사합니다.

refactor: 장소 도메인 메서드 컨벤션 수정 및 리팩토링

---

src/main/kotlin/kr/wooco/woocobe/common/ui/config/JacksonConfig.kt

`Long` 또는 `Double` 값을 JSON 으로 직렬화시 값이 유실되어 0 으로 표기되던 문제를 수정합니다.
- ✨ `Long` 값 및 `Double` 값 직렬화 로직 추가
- closed #103 
안전 범위 밖의 값일 경우 `String` 값으로 직렬화 하도록 수정했습니다.

fix: JSON 안전 범위 초과시 값이 유실되는 문제 수정

---

src/main/kotlin/kr/wooco/woocobe/place/domain/exception/PlaceExceptions.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/exception/PlaceReviewExceptions.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceOneLineReview.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceOneLineReviewStat.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceReview.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/UpdatePlaceReviewUseCase.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/PlaceReviewStorageGatewayImpl.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/PlaceStorageGatewayImpl.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewStatStorageMapper.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewStorageMapper.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewStorageMapper.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceOneLineReviewJpaEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceReviewJpaEntity.kt
src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/repository/PlaceOneLineReviewJpaRepository.kt
src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/PlaceReviewApi.kt
src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/PlaceReviewController.kt
src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/request/CreatePlaceReviewRequest.kt
src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/request/UpdatePlaceReviewRequest.kt
src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceOneLineReviewStatDetailResponse.kt
src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceReviewDetailsResponse.kt

- 장소 도메인의 예외를 정의하고, 에러 핸들링을 개선
- 회원이 작성 리뷰 리스트 API 엔드포인트 수정
1. **도메인 예외 처리 추가**  
- **장소 관련 예외**
- `NotExistsPlaceException`: 존재하지 않는 장소 요청 시 발생.
- `MissingPlaceOneLineReviewContentException`: 한줄평 내용 누락 시 발생.
- `MissingPlaceOneLineReviewCountException`: 한줄평 개수 누락 시 발생.
- **리뷰 관련 예외**
- `NotExistsPlaceReviewException`: 존재하지 않는 리뷰 요청 시 발생.
- `InvalidPlaceReviewWriterException`: 리뷰 작성자가 아닌 사용자가 수정/삭제를 시도할 경우 발생.
2. **예외 적용**
- `RuntimeException`을 도메인별 구체적인 예외 클래스로 대체.
3. **접근 제어자 수정**
- `PlaceReviewStorageGatewayImpl` 및 `PlaceStorageGatewayImpl`의 클래스 접근 제어자를 `internal`로 변경
4. **함수 파라미터 명 수정**
- `updateThumbnailUrl` 함수의 파라미터명을 `imageUrl` ->`thumbnailUrl`로 변경
5. **DTO 수정**
- `PlaceReviewDetailsResponse`에 `createdAt` 누락된  필드 추가.
6. **API 경로 및 파라미터 수정**  
- 경로 변경: `/my` → `/users/{userId}`
- 메서드 …

refactor: 장소 도메인 예외 처리 추가 및 개선

---

src/main/kotlin/kr/wooco/woocobe/plan/domain/exception/PlanExceptions.kt
src/main/kotlin/kr/wooco/woocobe/plan/domain/model/Plan.kt
src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanCategory.kt
src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/AddPlanUseCase.kt
src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/UpdatePlanUseCase.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/PlanStorageGatewayImpl.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanStorageMapper.kt
src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanJpaEntity.kt
src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/request/CreatePlanRequest.kt
src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/request/UpdatePlanRequest.kt
src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/response/PlanDetailResponse.kt

- 플랜 도메인 커스텀 예외를 추가 합니다.
- 플랜 도메인 API 응답 형식을 통일합니다.
- ✨ 플랜 도메인의 커스텀 예외 추가 및 적용
- ✨ 기존 `description` 필드명을 `contents`로 변경, API 응답 필드명 적용
- closed #117

feat: 플랜 도메인 커스텀 예외 추가 및 응답 형식 통일

---

src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/InterestCourseStorageGateway.kt
src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllUserInterestCourseUseCase.kt
src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/InterestCourseStorageGatewayImpl.kt
src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/InterestCourseJpaRepository.kt
src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseApi.kt
src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseController.kt
src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseQueryFacade.kt

관심 코스 조회시 최대 개수를 지정할 수 있도록 수정합니다.
- ✨ 관심 코스 조회시 `limit` 추가
- closed #121 
-

refactor: 관심 코스 조회시 최대 개수 지정 추가

---

core/src/main/kotlin/kr/wooco/woocobe/core/coursecomment/application/service/CourseCommentCommandService.kt
core/src/main/kotlin/kr/wooco/woocobe/core/coursecomment/domain/event/CourseCommentCreateEvent.kt

댓글 생성시 이벤트 발행 로직을 추가합니다.
- ✨ 댓글 생성시 스프링 내부 이벤트 발행 로직 추가
- ✨ 댓글 생성시 코스의 댓글 개수 증가 로직 추가
- closed #159 
현재 댓글 생성시 댓글 알림을 위해 필요한 데이터기 코스 작성자의 식별자(user_id)와 코스의 이름이 필요한 상태입니다.
일단 빠르게 구현하기 위해, 댓글 생성 유즈케이스 내에서 1. 댓글을 생성 2.해당 코스의 댓글 수 증가 3. 알림 이벤트 전송(코스 정보 + 댓글 작성자 정보) 를 발행하는 로직으로 구현되어있습니다.
구현된 부분이 SRP 위반일지 아닐지 한번더 고민 후 리팩토링 방향을 정해야할 것 같습니다.

feat: 댓글 생성 이벤트 발행 로직 추가

---

bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/place/PlaceController.kt
core/src/main/kotlin/kr/wooco/woocobe/core/place/application/handler/PlaceEventHandler.kt
core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/in/CreatePlaceIfNotExistsUseCase.kt
core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/in/UpdatePlaceImageUseCase.kt
core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/out/PlaceClientPort.kt
core/src/main/kotlin/kr/wooco/woocobe/core/place/application/service/PlaceCommandService.kt
core/src/main/kotlin/kr/wooco/woocobe/core/place/domain/entity/Place.kt
core/src/main/kotlin/kr/wooco/woocobe/core/place/domain/event/PlaceCreateEvent.kt
infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/common/config/RestConfig.kt
infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/GooglePlaceApiClient.kt
infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/GooglePlaceProperties.kt
infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/PlaceClientAdapter.kt
infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/response/GooglePlaceDetailsResponse.kt
infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/response/GooglePlaceIdResponse.kt
infrastructure/rest/src/main/resources/application-rest.yml

구글 PLACE API 를 통해 장소의 썸네일 이미지를 추출합니다.
- ✨ 구글 Place API 연동 로직 추가
- ✨ 장소 생성시 이벤트 발행 로직 추가
- closed #171 
- 장소 생성 유즈케이스의 네이밍이 불명확해서 유즈케이스 네이밍을 수정했습니다.
(`CreatePlaceUseCase` to `CreatePlaceIfNotExistsUseCase`)
- `updatePlaceImage` 에서 외부 API 호출이 물려있어 `@Transactional` 어노테이션을 적용하지 않았습니다.

feat: 장소 썸네일 이미지 추출 로직 추가

---

bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/PlaceReviewApi.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/PlaceReviewController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/response/PlaceReviewDetailsResponse.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/response/PlaceReviewWithPlaceDetailsResponse.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/response/PlaceReviewWithWriterDetailsResponse.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/ReadAllMyPlaceReviewUseCase.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/ReadAllPlaceReviewUseCase.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/ReadAllUserPlaceReviewUseCase.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/ReadPlaceReviewUseCase.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/result/PlaceReviewWithPlaceResult.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/result/PlaceReviewWithWriterResult.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/LoadPlaceReviewPersistencePort.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/service/PlaceReviewCommandService.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/service/PlaceReviewQueryService.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/entity/PlaceReview.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/event/PlaceReviewCreateEvent.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/event/PlaceReviewDeleteEvent.kt
core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/event/PlaceReviewUpdateEvent.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceReviewPersistenceAdapter.kt

- 여러 가지 버그 수정(파라미터 순서, 누락된 이미지 로직)과 **OneLineReviews 타입 변경**, **평점 유효성 검증 로직 추가**, **사용하지 않는 메서드 삭제** 등의 리팩토링을을 하였습니다.
1. **deletePlaceReview 파라미터 오류 수정**  
- `DeletePlaceReviewUseCase.Command` 생성 시 파라미터 순서가 잘못 전달되던 문제를 해결했습니다.
2. **OneLineReviews 타입을 `List<String>`으로 변경**  
-  단순 문자열 리스트로 관리하도록 수정하였습니다.
3. **누락된 이미지 엔티티 저장 로직 추가**  
- 리뷰 생성 시 이미지 엔티티가 올바르게 저장되도록 처리했습니다.
4. **사용하지 않는 `getAllByPlaceReviewIds` 메서드 삭제**  
- 필요하지 않은 PersistencePort 메서드를 제거했습니다.
5. **이벤트 객체를 팩토리 메서드로 반환하도록 리팩토링**  
- `PlaceReviewCreateEvent`, `PlaceReviewUpdateEvent`, `PlaceReviewDeleteEvent` 팩토리 메서드를 통해 이벤트 객체를 생성하도록 변경했습니다.
6. **리뷰 평점 유효성 검증 로직 추가**  
- `PlaceReview` 엔티티 생성 시 평점이 1.0 ~ 5.0 범위를 벗어나지 않도록 도메인 레벨에서 검증을 추가했습니다.
7. **User 리뷰 리스트 조회 시 장소 이름이 포함되도록 수정**  
- `getAllMyPlaceReview` 응답이 장소 …

fix : PlaceReview 에러 수정 및 응답 구조 변경

---

core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/scheduler/PlanScheduler.kt

- 플랜 공유 알림 생성을 위한 스케줄링 주기를 변경합니다.
- ✨ 플랜 공유 알림 생성을 위한 스케줄링 주기를 1시간에 한 번 -> 매일 자정으로 변경
- closed #181 
- 기존 1시간에 한 번씩 공유되지 않은 플랜에 대한 공유 요청 알림을 생성했으나, 아직 중복 알림에 대한 관리를 하지 않아 알림이 많이 생성되고 있습니다. 이에 급한대로 스케줄링 주기를 하루에 한 번(매일 자정)으로 변경하였습니다.

fix: 과도한 플랜 공유 알림 생성으로 인한 스케줄링 주기 변경

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
infrastructure/mysql/build.gradle.kts
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/entity/PlanPlaceJpaEntity.kt
infrastructure/mysql/src/main/resources/application-mysql.yml
infrastructure/mysql/src/main/resources/db/migration/V1__init.sql

db 마이그레이션 툴 `flyway` 적용 및 `prod` 배포 스크립트 추가합니다
- ✨ flyway 의존성 추가
- ✨ 초기 ddl 스크립트(`V1__init.sql` ) 추가
- ✨ prod 배포 스크립트 추가
- ✨ dev 배포 스크립트 환경변수 이름 수정
- closed #187 
jpa의 `ddl-auto` 옵션 기본값을 `validate`로 수정했습니다
현재 오토스케일링을 고려하지 않은 상태라서 개별 인스턴스로의 배포만 가능한 상태입니다
만약, 서비스 사용자가 계속해서 증가하는 추세가 보인다면 ECS 로 마이그레이션 진행예정입니다.

build: flyway 의존성 추가 및 prod 배포 스크립트 추가

---

core/src/main/kotlin/kr/wooco/woocobe/core/course/application/service/CourseQueryService.kt

코스 상세 조회시 관심 여부가 정상적으로 반환되지 않는 버그 수정
- ✨ `userId`와 `courseId`가 식별자값이 반대로 되어있었던 버그 수정
- closed #191 
-

fix: 코스 상세 조회시 관심 여부 반환 버그 수정

---

core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/out/DeletePlanPersistencePort.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/out/PlanCommandPort.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/out/PlanQueryPort.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/scheduler/PlanScheduler.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/service/PlanCommandService.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/service/PlanQueryService.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/domain/entity/Plan.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPersistenceAdapter.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPersistenceMapper.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPlacePersistenceMapper.kt

- 플랜 도메인 out 포트 네이밍 및 어댑터 컨벤션을 통일합니다.
- 플랜 도메인 클래스 내 필드를 불변으로 변경합니다.
- ✨ Out port 를 `PlanCommandPort`, `PlanQueryPort` 로 통합
- ✨ 매퍼 클래스 `object`로 변경
- ✨ 플랜 도메인 클래스 내 필드 불변으로 변경
- closed #200

refactor: 플랜 도메인 포트 및 어댑터 등 컨벤션 통일

---

bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/auth/AuthController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/common/config/WebSecurityConfig.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/common/security/SecurityIgnorePath.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/course/CourseController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/coursecomment/CourseCommentController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/image/ImageController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/notification/NotificationController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/place/PlaceController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/PlaceReviewController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/plan/PlanController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/region/RegionController.kt
bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/user/UserController.kt
infrastructure/rest/src/main/resources/application-rest.yml
support/metric/src/main/resources/application-metric.yml

DEV 서버에서 발생하고 있는 500에러 해결 및 엑츄에이터 리스너 포트 번호를 수정합니다.
- ✨ `@PreAuthorize` 제거
- ✨ 엑츄에이터 리스닝 포트 수정 (`8080` -> `9000`)
- closed #205 
- #204 에서 추가 작업했던 `@PreAuthorize` 를 통한 인증 엔드포인트 관리 로직을 롤백했습니다.

fix: PreAuthorize 버그 해결 및 엑츄에이터 포트 수정

---

core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/out/DeviceTokenCommandPort.kt
core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/service/NotificationCommandService.kt
core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/DeviceToken.kt
core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/Notification.kt
core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/vo/DeviceTokenStatus.kt
core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/vo/NotificationStatus.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/out/PlanCommandPort.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/service/PlanCommandService.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/domain/entity/Plan.kt
core/src/main/kotlin/kr/wooco/woocobe/core/plan/domain/vo/PlanStatus.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/DeviceTokenJpaAdapter.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/DeviceTokenJpaMapper.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/NotificationJpaAdapter.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/NotificationJpaMapper.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/entity/DeviceTokenJpaEntity.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/entity/NotificationJpaEntity.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/repository/DeviceTokenJpaRepository.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/repository/NotificationJpaRepository.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanJpaAdapter.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanJpaMapper.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPlaceJpaMapper.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/entity/PlanJpaEntity.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/repository/PlanJpaRepository.kt
infrastructure/mysql/src/main/resources/db/migration/V4__add_status_notifications_and_plans.sql

- 알림 및 플랜 도메인 `soft delete` 적용
- 기타 매퍼, 어댑터 네이밍 등 컨벤션 통일
- ✨ `notifications`, `device_tokens`, `plans` 테이블에 `status` 필드를 추가함에 따라 flyway 마이그레이션 파일을 추가했습니다.
- ✨ 각 도메인 엔티티에서 `soft delete`를 위한 메서드를 추가, 커멘드 서비스에서 이를 호출하도록 변경했습니다.
- ✨ 각 레포지토리의 조회 쿼리에 `ACTIVE` 상태 조건을 추가했습니다. 
- ✨ 기존 `xxxPersistenceMapper`, `xxxPersistenceAdapter` 네이밍을 `xxxJpaMapper`, `xxxJpaAdapter`로 변경했습니다.
- ✨ 각 도메인 엔티티의 `validateOwner()` 메서드를 private 으로 변경했습니다.
- closed #202
- 현재 `soft delete` 적용시 도메인 클래스에서 상태를 바꾸고, 커멘드 서비스에서 이를 `save`메서드로  저장합니다. 만약 더 좋은 방법이 있다면 알려주세요!!!
- `Notification` 은 직접적으로 삭제하는 기능이 없어 도메인 클래스 내에서 `soft delete` 메서드만 구현하고, 이를 위한 엔드포인트는 만들지 않았습니다. 만약 추가될 경우 컨트롤러에서만 추가하면 됩니다.

refactor: 알림, 플랜 도메인 soft delete 적용 및 네이밍 변경

---

bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/common/config/AsyncConfig.kt
core/build.gradle.kts
core/src/main/kotlin/kr/wooco/woocobe/core/common/aspect/EventPublisherAspect.kt
core/src/main/kotlin/kr/wooco/woocobe/core/common/domain/entity/AggregateRoot.kt
core/src/main/kotlin/kr/wooco/woocobe/core/common/domain/entity/DomainEntity.kt
core/src/main/kotlin/kr/wooco/woocobe/core/common/domain/event/DomainEvent.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/advice/CustomJpaRepositoryFactoryBean.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/advice/EventPublishingMethodInterceptor.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/config/MysqlConfig.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/entity/BaseEntity.kt
infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/utils/Tsid.kt
support/common/src/main/kotlin/kr/wooco/woocobe/common/event/Event.kt
support/common/src/main/kotlin/kr/wooco/woocobe/common/event/EventContext.kt

이벤트 발행 로직을 개선합니다.
- ✨ 쓰레드 개별 이벤트를 저장할 수 있는 EventContext 클래스 추가
- ✨ 기본 AggregateRoot 및 DomainEntity 클래스 추가
- ✨ 애플리케이션 레이어에서 명시적으로 `ApplicationEventPublisher` 를 사용하던 부분 개선
- ✨ Async 쓰레드에서 정상적으로 MDC 컨텍스트가 복사되지 않는 버그 해결
- closed #195 
기존에 애플리케이션 레이어에서 `ApplicationEventPublisher` 를 통해 이벤트를 명시적으로 발행시켜 부자연스러웠던 부분을
도메인 엔티티에서 이벤트 등록 후 영속화가 완료된 뒤 이벤트가 인터셉터 또는 AOP를 통해 발행되도록 개선하였습니다.
동작 방식은 AggregateRoot 내 `registerEvent()` 메서드를 통해 
도메인 엔티티내에서 EventContext에 정의된 `eventStore` 즉,ThreadLocal 내 이벤트를 "등록"하며, 
Spring Data JPA의 `save()` 관련 메서드를 호출하거나 서비스 로직이 종료될때 이벤트가 "발행"됩니다.
도메인 엔티티 내에서는 이벤트 등록을, 도메인 외부에서 이벤트가 실제 발행되는 것을 인지하셔야합니다.
세부 내용은 EventContext, AggregateRoot 등 현 PR에서 추가된 클래스 안에 헷갈리지 않도록 주석을 달아놨습니다.

refactor: 이벤트 발행 로직 개선

---

core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/service/NotificationQueryService.kt
infrastructure/fcm/src/main/kotlin/kr/wooco/woocobe/fcm/notification/FcmNotificationSenderAdapter.kt

- FCM 알림 전송시 디바이스 토큰이 없는 경우 발생하는 예외를 핸들링하기 위한 PR입니다.
- ✨ 알림 전송 전 디바이스 토큰이 비어있다면 전송을 하지 않도록 조건 변경
- closed #209
- 실시간 알림은 FCM, 알림 목록 조회는 DB 기반 API로 분리되어 있습니다. 따라서 `FCM 실패 = "실시간 전송 실패"` 일 뿐, 알림 자체는 유실되지 않기 때문에 특정 예외를 발생시키지 않고 해당 메서드를 종료하도록 구현했습니다. 
- 만약 추후에 전송 상태를 핸들링하도록 정책이 바뀐다면, 해당 상황에 맞게 리팩토링하면 될 것 같습니다. 이에 전송 실패시 디바이스 토큰이 없는 유저 아이디만 로그에 남기도록 했습니다.

fix: FCM 전송시 디바이스 토큰이 없는 경우 발생하는 예외 해결
